import Head from 'next/head';
import Nav from '../components/Nav'


export default function Home() {
  return (
    <div>
       <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <main><h2 className="text-2xl mt-10">Confirm your professional skillls</h2></main>
    </div>
  )
}


